In [1]:
# numpy 라이브러리 import하기
# dkvdmfh np라는 이름으로 부르기
import numpy as np

In [6]:
list1=[1,2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [7]:
#array생성하기
arr=np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [9]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
#리스트
#[1,2,3] , [4,5,6] 각 요성의 값을 더한다.

In [15]:
list1 = [1,2,3]
list2 = [4,5,6]


In [17]:
arr3 = np.array(list1)
arr4 = np.array(list2)

In [18]:
arr5 = arr3 + arr4
arr5

array([5, 7, 9])

In [ ]:
#list3=[]
#for i in range(3):
#    list3.append(list1[i]+list2[i])
#list3

In [27]:
#2차원 array 생성하기
arr6 = np.array( [ [ 1,2,3 ],[ 4,5,6 ] ] )
arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#array 의 크기 확인하기
#shape
arr6.shape

(2, 3)

In [28]:
#array전체 요소 개수 확인하기
#size 
arr6.size

6

In [30]:
#array 타입 확인하기
#dtype
arr6.dtype

dtype('int32')

In [32]:
#array 차원 확인하기
#ndim
arr6.ndim

2

In [33]:
#3차원의 array 만들고 배열의 크기, 차원 , 전체 요소 개수 확인
arr7 = np.array(   [   [   [1,2],[3,4]   ],[   [5,6],[7,8]   ]   ]   )
arr7

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [41]:
print('배열의 크기', arr7.shape)

배열의 크기 (2, 2, 2)


In [42]:
print('배열의 요소개수' , arr7.size)

배열의 요소개수 8


In [43]:
print('배열의 차원', arr7.ndim)

배열의 차원 3


In [44]:
print('배열의 타입', arr7.dtype)

배열의 타입 int32


In [47]:
print('배열의 크기:{}'.format(arr7.shape))
print(f'배열의 차원:{arr7.ndim}')
print('배열의 개수:', arr7.size)

배열의 크기:(2, 2, 2)
배열의 차원:3
배열의 개수: 8


In [48]:
#배열 생성하기

# 0의 박으로 배열 생성하기
# zeros(배열의 크기)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
# 1 값으로 생성하기
#ones()
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
#지정해서 생성하기
#full(배열의 크기, 채워넣을 값)
np.full((3,4),5)
       # 3개의 배열 4개의 값이 들어갈수 있게 , 5 라는 값으로 넣어서 만들어라~~~  


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [56]:
#연속되는 숫자로 배열 생성하기
#arange( 시작하는 수, 끝나는 수 +1, 간격이 되는 수)
#시작되는 수 기본 값 : 0
#간격이 되는 수 기본값 :1
np.arange(1, 50+1, 10)

array([ 1, 11, 21, 31, 41])

In [57]:
np.arange(1, 50, 10)

array([ 1, 11, 21, 31, 41])

In [58]:
np.arange(1,42,10)

array([ 1, 11, 21, 31, 41])