In [2]:
# numpy 라이브러리 import하기
# 앞으로 np라는 이름으로 부르기
import numpy as np

In [3]:
list1=[1,2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [4]:
#array생성하기
arr=np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [5]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
#리스트
#[1,2,3] , [4,5,6] 각 요성의 값을 더한다.

In [7]:
list1 = [1,2,3]
list2 = [4,5,6]


In [8]:
arr3 = np.array(list1)
arr4 = np.array(list2)

In [9]:
arr5 = arr3 + arr4
arr5

array([5, 7, 9])

In [10]:
#list3=[]
#for i in range(3):
#    list3.append(list1[i]+list2[i])
#list3

In [11]:
#2차원 array 생성하기
arr6 = np.array( [ [ 1,2,3 ],[ 4,5,6 ] ] )
arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#array 의 크기 확인하기
#shape
arr6.shape

(2, 3)

In [13]:
#array전체 요소 개수 확인하기
#size 
arr6.size

6

In [14]:
#array 타입 확인하기
#dtype
arr6.dtype

dtype('int32')

In [15]:
#array 차원 확인하기
#ndim
arr6.ndim

2

In [16]:
#3차원의 array 만들고 배열의 크기, 차원 , 전체 요소 개수 확인
arr7 = np.array(   [   [   [1,2],[3,4]   ],[   [5,6],[7,8]   ]   ]   )
arr7

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
print('배열의 크기', arr7.shape)

배열의 크기 (2, 2, 2)


In [18]:
print('배열의 요소개수' , arr7.size)

배열의 요소개수 8


In [19]:
print('배열의 차원', arr7.ndim)

배열의 차원 3


In [20]:
print('배열의 타입', arr7.dtype)

배열의 타입 int32


In [21]:
print('배열의 크기:{}'.format(arr7.shape))
print(f'배열의 차원:{arr7.ndim}')
print('배열의 개수:', arr7.size)

배열의 크기:(2, 2, 2)
배열의 차원:3
배열의 개수: 8


In [22]:
#배열 생성하기

# 0의 값으로 배열 생성하기  => 0으로 초기화
# zeros(배열의 크기)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# 1 값으로 생성하기 => 1호 초기화
#ones()
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#지정해서 생성하기
#full(배열의 크기, 채워넣을 값)
np.full((3,4),5)
       # 3개의 배열 4개의 값이 들어갈수 있게 , 5 라는 값으로 넣어서 만들어라~~~  


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [25]:
#연속되는 숫자로 배열 생성하기
#arange( 시작하는 수, 끝나는 수 +1, 간격이 되는 수)
#시작되는 수 기본 값 : 0
#간격이 되는 수 기본값 :1
np.arange(1, 50+1, 10)

array([ 1, 11, 21, 31, 41])

In [26]:
np.arange(1, 50, 10)

array([ 1, 11, 21, 31, 41])

In [27]:
np.arange(1,42,10)

array([ 1, 11, 21, 31, 41])

In [29]:
#1부터 50까지 1씩 커지는 배열 만들기
#np.linspace(시작하는수, 끝나는 수, 등분할 값)

#같은 간격만틈의 배열을 만들때 사용

np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [31]:
#for문으로 사용할 수 있다. 
for i in np.linspace(1,50,20):
    print(i)

1.0
3.5789473684210527
6.157894736842105
8.736842105263158
11.31578947368421
13.894736842105264
16.473684210526315
19.05263157894737
21.63157894736842
24.210526315789473
26.789473684210527
29.36842105263158
31.94736842105263
34.526315789473685
37.10526315789474
39.68421052631579
42.26315789473684
44.8421052631579
47.421052631578945
50.0


In [32]:
#랜덤값으로 배열 생성하기
# np.random.rand(배열의 크기)
# 0 ~ 1 사이의 값을 가지는 배열을 생성
np.random.rand(2,3)

array([[0.47948632, 0.6763012 , 0.93950948],
       [0.87648343, 0.24222092, 0.22736462]])

In [34]:
#내가 원하는 범위 안에서 랜덤값 생성
#np.random.randit(시작수, 끝수+1, size = 배열의 크기)

np.random.randint(2,10,size=(3,2))

array([[4, 3],
       [7, 8],
       [6, 6]])

In [38]:
#2부터 10까지의 런덤 실수값으로 이루어진 (5,4) 크기의 배열 생성

np.random.rand(2,10) , np.random.randint(2,10, size=(5,4))

(array([[0.1329847 , 0.26360026, 0.36853114, 0.67040817, 0.83427497,
         0.08815366, 0.0333611 , 0.97667894, 0.91910292, 0.74013946],
        [0.97175941, 0.31299074, 0.95404795, 0.11520977, 0.122742  ,
         0.94414633, 0.75248567, 0.51844305, 0.82297856, 0.37082727]]),
 array([[8, 6, 3, 9],
        [5, 4, 6, 7],
        [2, 8, 5, 9],
        [6, 5, 2, 9],
        [6, 4, 2, 4]]))

In [40]:
#정수+소수점 = 실수
정수 = np.random.randint(2,10 , size=(5,4))
정수

array([[7, 2, 7, 4],
       [9, 6, 6, 9],
       [3, 3, 7, 8],
       [3, 9, 7, 6],
       [5, 9, 9, 6]])

In [41]:
소수점 = np.random.rand(5,4)
소수점

array([[0.9418698 , 0.99594831, 0.03974279, 0.98450692],
       [0.49183177, 0.94184123, 0.43506132, 0.02410503],
       [0.59511425, 0.42664226, 0.62864937, 0.12772594],
       [0.22621436, 0.35058713, 0.21594569, 0.36888681],
       [0.55183373, 0.28830255, 0.16983368, 0.13995559]])

In [42]:
실수=정수+소수점
실수

array([[7.9418698 , 2.99594831, 7.03974279, 4.98450692],
       [9.49183177, 6.94184123, 6.43506132, 9.02410503],
       [3.59511425, 3.42664226, 7.62864937, 8.12772594],
       [3.22621436, 9.35058713, 7.21594569, 6.36888681],
       [5.55183373, 9.28830255, 9.16983368, 6.13995559]])

In [47]:
abc = np.random.rand(5,4) + np.random.randint(2,10, size=(5,4))
print(abc)

[[8.95200988 7.40168891 6.82786356 2.04870459]
 [9.47323286 9.92518498 7.24001561 8.97279167]
 [5.52147713 8.29891283 8.25519986 2.36364721]
 [7.10026691 8.70527536 4.38555053 4.59868106]
 [4.44356873 4.29247907 7.82363167 6.47186067]]


In [ ]:
#타입 변경하기
# 배열.astype(변경할 타입)


In [44]:
실수.astype('int')

array([[7, 2, 7, 4],
       [9, 6, 6, 9],
       [3, 3, 7, 8],
       [3, 9, 7, 6],
       [5, 9, 9, 6]])

In [ ]:
#배열의 생성

In [ ]:
#배열의 기능

In [48]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
#인덱싱
#[대괄호]
# 2차원에서 0번째 출력
arr[0]
arr[0][1]

2

In [54]:
arr[0,1]
#2차원에서 1번 선택해서 1차원에서 1번째 선택

2

In [ ]:
#슬라이싱

In [ ]:
#0~9 까지의 값이 담긴 배열 생성

In [56]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 3부터 7까지의 값 출력

In [61]:
arr1[3:8]

array([3, 4, 5, 6, 7])

In [62]:
#2차원 슬라이싱
# 0~49까지 정수의 값이 담겨있는 array생성하기
arr2=np.arange(50)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
#arr2를 (5,10)으로 재 배열하기
#reshape
#바뀌기 전과 후의 데이터 수가 똑같아야함

#arr2.reshape(5,10)
#출력을 진행하고 저장은 진행되지 않음, 변수에 담아줘야 저장이 됨
arr2 = arr2.reshape(5,10)

In [67]:
#2차원 슬라이싱
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
# [고차원, 1차원]

In [ ]:
#어떤식의 인덱스 번호가 부여 되어 있는지 확인 
#

In [68]:
arr2[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [69]:
arr2[0:2, 0:10]   #위와 같은 출력

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [70]:
#전체 출력
#시작수 : 끝수+1
# : 끝수 +1 =처음부터 끈수까지
# 시작수 : = 시작수부터 끝까지
# : = 처음부터 끝까지
arr2[0:2, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [75]:
arr2[0:4, 0:5]   #[:4, :5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [74]:
arr2[0:5, 0:1]   #[:,0]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [ ]:
# 위 키(cm)
#아래 몸무게(kg)
# 10개의 데이터
#bmi 계산하기


In [78]:
#파일 불러오기

data = np.loadtxt('height_weight.txt', delimiter=',')
data


array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [108]:
bmi=[]

for i in range(0,10):
    bmi.append(data[1,i]/(data[0,i]/data[0,i]*10000)

print(bmi)


#print(round(bmi, 8))  소수점 맞추어 주기

SyntaxError: invalid syntax (Temp/ipykernel_9536/1216300796.py, line 6)

In [131]:
d = "format example4 : {1:.2f} / {0:.1f}".format(3.22521321, 10.123456)
print(d)

format example4 : 10.12 / 3.2


In [88]:
height=data[0] /100
weight=data[1]
bmi = weight/ height**2
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [95]:
키_cm = data[0]
키_cm

array([175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
       179. ])

In [99]:
키_m = 키_cm /100
키_m

array([1.752, 1.803, 1.75 , 1.692, 1.852, 1.88 , 1.776, 1.782, 1.77 ,
       1.79 ])

In [97]:
몸무게 = data[1]
몸무게

array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ])

In [101]:
몸무게 / (키_m*키_m)

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

# Boolean 인덱싱
#True 는 출력하고 False 는 출력하지 않음
#인덱싱을 진행할떄 개수와 동일한 수의 Boolean data필요
#원하는 조건에 맞는 값을 출력하는 방법

In [110]:
arr3 = np.array([10,20,15,30])
arr3

array([10, 20, 15, 30])

In [ ]:
# 20,30 F  , 10,15 T


In [111]:
bol=np.array([True, False, True, False])   #비효율적
bol

array([ True, False,  True, False])

In [112]:
arr3[bol]

array([10, 15])

In [113]:
arr3 < 17

array([ True, False,  True, False])

In [115]:
arr3[bol]

array([10, 15])

In [114]:
#17미만의 값만 출력
arr3[arr3<17]

array([10, 15])

In [119]:
# arr3 에서 20인 값만 출력

print(arr3 == 20)

[False  True False False]


In [121]:
print(arr3[arr3 == 20])

[20]


In [120]:
arr3[arr3 == 20]

array([20])

In [118]:
arr3[arr3 != 20]

array([10, 15, 30])

In [ ]:
# numpy에서 사용하는 연산 함수

In [ ]:
#1~9 까지의 랜덤한 수가 담긴 (2,5) 크기의 배열 생성

In [123]:
arr = np.random.randint(1,10,size=(2,5))
arr

array([[7, 5, 9, 4, 1],
       [8, 7, 2, 4, 4]])

In [126]:
#배열 안에 있는 값 더하기
#np.sum(배열값)
np.sum(arr)

51

In [127]:
np.sum(arr, axis = 0)
#axis 각 요소 끼리 1차원 0, 

array([15, 12, 11,  8,  5])

In [128]:
np.sum(arr, axis = 1)
# 2차원일경우 1 

array([26, 25])

In [129]:
#배열 안에 있는 값의 평균
#np.mean(배열값)

np.mean(arr)

5.1

In [130]:
np.mean(arr,axis = 1)

array([5.2, 5. ])